version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  client-container:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "3001:3001"

  api-container:
    build: ./api
    container_name: server
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./api/src:/app/src
      - ./api/dist:/app/dist
    ports:
      - "3000:3000"
    environment:
      TOKEN: eitanBeshok
      SECRET: eitanTheKingLikeFish
      PASSWORD: root
      DATABASE: northwind
      DB_PORT: 3306
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: apppass
      NODE_ENV: development
    command: npm run all
    depends_on:
      - mysql
